name: Java CI

on:
  push:
    branches:
      - master
      - dev
    paths:
      - '**.java'
      - '**.gradle'
      - '**/workflows/**.yml'
  pull_request:
    branches:
      - master
      - dev


jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        java: [ '17' ]
    name: Sync Single-Thread Benchmark

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1

        with:
          java-version: ${{ matrix.java }}

      - name: Code Style
        run: ./gradlew spotlessCheck

      - name: Build
        run: ./gradlew shadowJar

      - name: Benchmark [goodforgod-simple-logger]
        run: java -jar goodforgod-simple-logger/build/libs/*-all.jar 2>/dev/null 2 6

      - name: Benchmark [logback-logger]
        run: java -jar logback-logger/build/libs/*-all.jar 2>/dev/null 2 6

      - name: Benchmark [log4j-logger]
        run: java -jar log4j-logger/build/libs/*-all.jar 2>/dev/null 2 6

      - name: Benchmark [slf4j-simple-logger]
        run: java -jar slf4j-simple-logger/build/libs/*-all.jar 2>/dev/null 2 6

      - name: Benchmark [system-logger]
        run: java -jar system-logger/build/libs/*-all.jar 2>/dev/null 2 6


  sync-multi-thread:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        java: [ '17' ]
    name: Sync Multi-Thread Benchmark

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1

        with:
          java-version: ${{ matrix.java }}

      - name: Code Style
        run: ./gradlew spotlessCheck

      - name: Build
        run: ./gradlew shadowJar

      - name: Benchmark [goodforgod-simple-logger]
        run: java -jar goodforgod-simple-logger/build/libs/*-all.jar 2>/dev/null 2 6 500

      - name: Benchmark [logback-logger]
        run: java -jar logback-logger/build/libs/*-all.jar 2>/dev/null 2 6 500

      - name: Benchmark [log4j-logger]
        run: java -jar log4j-logger/build/libs/*-all.jar 2>/dev/null 2 6 500

      - name: Benchmark [slf4j-simple-logger]
        run: java -jar slf4j-simple-logger/build/libs/*-all.jar 2>/dev/null 2 6 500

      - name: Benchmark [system-logger]
        run: java -jar system-logger/build/libs/*-all.jar 2>/dev/null 2 6 500
